spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CUHK_Web
    username: root
    password: xuzihang123
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB